trigger:
- main

variables:
  # Docker hub images
  frontendImage: 'jyothika2832/billing-backend:latest'
  backendImage: 'jyothika2832/billing-frontend:latest'
  mysqlImage: 'mysql:5.7'
  # Azure resources
  azureSubscription: 'azure-resource-manager-service-connection'
  kubernetesServiceConnection: 'my-aks-connection' # New service connection for kubectl
  resourceGroup: 'practise-rg'
  aksCluster: 'my-aks-cluster'
  location: 'eastus'
  namespace: 'production'
  nodeCount: 2
  vmSize: 'Standard_B2s'

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Provision_AKS
    displayName: 'Provision AKS Cluster'
    jobs:
      - job: Create_Cluster
        steps:
        - task: AzureCLI@2
          displayName: 'Create Resource Group'
          inputs:
            azureSubscription: $(azureSubscription)
            scriptType: 'bash'
            scriptLocation: 'inlineScript'
            inlineScript: |
              az group create \
                --name $(resourceGroup) \
                --location $(location)
        
        - task: AzureCLI@2
          displayName: 'Create or Update AKS Cluster'
          inputs:
            azureSubscription: $(azureSubscription)
            scriptType: 'bash'
            scriptLocation: 'inlineScript'
            inlineScript: |
              # Check if cluster exists
              if az aks show --resource-group $(resourceGroup) --name $(aksCluster) --query name -o tsv 2>/dev/null; then
                echo "Cluster exists - updating..."
                az aks update \
                  --resource-group $(resourceGroup) \
                  --name $(aksCluster) \
                  --node-count $(nodeCount)
              else
                echo "Cluster does not exist - creating..."
                az aks create \
                  --resource-group $(resourceGroup) \
                  --name $(aksCluster) \
                  --node-count $(nodeCount) \
                  --node-vm-size $(vmSize) \
                  --enable-addons monitoring \
                  --generate-ssh-keys \
                  --location $(location)
              fi
              
              # Get credentials
              mkdir -p $(Pipeline.Workspace)/kube
              az aks get-credentials \
                --resource-group $(resourceGroup) \
                --name $(aksCluster) \
                --overwrite-existing \
                --file $(Pipeline.Workspace)/kube/config


  - stage: Configure_Kubernetes
    displayName: 'Configure Kubernetes Access'
    dependsOn: Provision_AKS
    jobs:
    - job: Configure
      steps:
        - task: AzureCLI@2
          displayName: 'Get AKS Credentials'
          inputs:
            azureSubscription: $(azureSubscription)
            scriptType: 'bash'
            scriptLocation: 'inlineScript'
            inlineScript: |
              az aks get-credentials \
                --resource-group $(resourceGroup) \
                --name $(aksCluster) \
                --overwrite-existing \
                --file kubeconfig
              
              # Display cluster info for verification
              kubectl --kubeconfig=kubeconfig cluster-info

        - task: Kubernetes@1
          displayName: 'Create Namespace'
          inputs:
            kubernetesServiceEndpoint: $(kubernetesServiceConnection)
            command: 'apply'
            useConfigurationFile: true
            configuration: |
              apiVersion: v1
              kind: Namespace
              metadata:
                name: $(namespace)

  - stage: Deploy_Application
    displayName: 'Deploy Application'
    dependsOn: Configure_Kubernetes
    jobs:
    - job: Deploy
      steps:
        - task: Kubernetes@1
          displayName: 'Create MySQL secrets'
          inputs:
            kubernetesServiceEndpoint: $(kubernetesServiceConnection)
            command: 'apply'
            useConfigurationFile: true
            configuration: |
              apiVersion: v1
              kind: Secret
              metadata:
                name: mysql-secrets
                namespace: $(namespace)
              type: Opaque
              data:
                root-password: $(echo -n 'your-root-password' | base64)
                username: $(echo -n 'your-db-user' | base64)
                password: $(echo -n 'your-db-password' | base64)

        - task: KubernetesManifest@1
          displayName: 'Deploy MySQL'
          inputs:
            kubernetesServiceEndpoint: $(kubernetesServiceConnection)
            action: 'deploy'
            namespace: $(namespace)
            manifests: |
              $(Pipeline.Workspace)/manifests/mysql-deployment.yaml
              $(Pipeline.Workspace)/manifests/mysql-service.yaml

        - task: Bash@3
          displayName: 'Wait for MySQL'
          inputs:
            targetType: 'inline'
            script: |
              kubectl --kubeconfig=kubeconfig wait --namespace $(namespace) --for=condition=ready pod -l app=mysql --timeout=300s

        - task: KubernetesManifest@1
          displayName: 'Deploy Backend'
          inputs:
            kubernetesServiceEndpoint: $(kubernetesServiceConnection)
            action: 'deploy'
            namespace: $(namespace)
            manifests: |
              $(Pipeline.Workspace)/manifests/backend-deployment.yaml
              $(Pipeline.Workspace)/manifests/backend-service.yaml

        - task: KubernetesManifest@1
          displayName: 'Deploy Frontend'
          inputs:
            kubernetesServiceEndpoint: $(kubernetesServiceConnection)
            action: 'deploy'
            namespace: $(namespace)
            manifests: |
              $(Pipeline.Workspace)/manifests/frontend-deployment.yaml
              $(Pipeline.Workspace)/manifests/frontend-service.yaml

        - task: Bash@3
          displayName: 'Get Frontend URL'
          inputs:
            targetType: 'inline'
            script: |
              echo "##vso[task.setvariable variable=frontendUrl]http://$(kubectl --kubeconfig=kubeconfig get svc frontend -n $(namespace) -o jsonpath='{.status.loadBalancer.ingress[0].ip}')"
              echo "Access your application at: http://$(kubectl --kubeconfig=kubeconfig get svc frontend -n $(namespace) -o jsonpath='{.status.loadBalancer.ingress[0].ip}')"
