trigger:
- main

variables:
  # Docker hub images
  frontendImage: 'jyothika2832/billing-backend:latest'
  backendImage: 'jyothika2832/billing-frontend:latest'
  mysqlImage: 'mysql:5.7'
  # Azure resources
  azureSubscription: 'azure-resource-manager-service-connection'
  kubernetesServiceConnection: 'my-aks-connection'
  resourceGroup: 'practise-rg'
  aksCluster: 'my-aks-cluster'
  location: 'eastus'
  namespace: 'production'
  nodeCount: 2
  vmSize: 'Standard_B2s'

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Provision_AKS
    displayName: 'Provision AKS Cluster'
    jobs:
      - job: Create_Cluster
        steps:
        - task: AzureCLI@2
          displayName: 'Create Resource Group'
          inputs:
            azureSubscription: $(azureSubscription)
            scriptType: 'bash'
            scriptLocation: 'inlineScript'
            inlineScript: |
              az group create \
                --name $(resourceGroup) \
                --location $(location)
        
        - task: AzureCLI@2
          displayName: 'Create or Update AKS Cluster'
          inputs:
            azureSubscription: $(azureSubscription)
            scriptType: 'bash'
            scriptLocation: 'inlineScript'
            inlineScript: |
              if az aks show --resource-group $(resourceGroup) --name $(aksCluster) --query name -o tsv 2>/dev/null; then
                echo "Cluster exists - checking current node count..."
                CURRENT_NODES=$(az aks show \
                  --resource-group $(resourceGroup) \
                  --name $(aksCluster) \
                  --query agentPoolProfiles[0].count -o tsv)
                
                if [ "$CURRENT_NODES" -ne $(nodeCount) ]; then
                  echo "Scaling node pool from $CURRENT_NODES to $(nodeCount)..."
                  az aks nodepool scale \
                    --resource-group $(resourceGroup) \
                    --cluster-name $(aksCluster) \
                    --name nodepool1 \
                    --node-count $(nodeCount)
                else
                  echo "Node count already matches desired count ($(nodeCount)) - no scaling needed"
                fi
              else
                echo "Cluster does not exist - creating..."
                az aks create \
                  --resource-group $(resourceGroup) \
                  --name $(aksCluster) \
                  --node-count $(nodeCount) \
                  --node-vm-size $(vmSize) \
                  --enable-addons monitoring \
                  --generate-ssh-keys \
                  --location $(location)
              fi


  - stage: Configure_Kubernetes
    displayName: 'Configure Kubernetes Access'
    jobs:
    - job: Configure
      steps:
        - task: KubectlInstaller@0
          displayName: 'Install kubectl'

        - task: AzureCLI@2
          displayName: 'Get AKS Credentials'
          inputs:
            azureSubscription: $(azureSubscription)
            scriptType: 'bash'
            scriptLocation: 'inlineScript'
            inlineScript: |
              mkdir -p $(Pipeline.Workspace)/kubeconfig
              az aks get-credentials \
                --resource-group $(resourceGroup) \
                --name $(aksCluster) \
                --admin \
                --file $(Pipeline.Workspace)/kubeconfig/config
              
              # Verify config file was created
              ls -la $(Pipeline.Workspace)/kubeconfig/
              if [ ! -f "$(Pipeline.Workspace)/kubeconfig/config" ]; then
                echo "##vso[task.logissue type=error]Failed to create kubeconfig file"
                exit 1
              fi
              
              # Print cluster info for debugging
              export KUBECONFIG=$(Pipeline.Workspace)/kubeconfig/config
              kubectl config view
              kubectl cluster-info || true

        - script: |
            echo "Current KUBECONFIG: $KUBECONFIG"
            ls -la $(Pipeline.Workspace)/kubeconfig/
            
            # Explicitly set KUBECONFIG
            export KUBECONFIG=$(Pipeline.Workspace)/kubeconfig/config
            
            # Verify kubectl can connect
            kubectl cluster-info
            
            # Create namespace
            kubectl create namespace $(namespace) --dry-run=client -o yaml | kubectl apply -f - --validate=false
            
            # Verify namespace
            kubectl get namespace $(namespace)
          displayName: 'Setup Kubernetes Access'
          env:
            KUBECONFIG: $(Pipeline.Workspace)/kubeconfig/config


  - stage: Deploy_Application
    displayName: 'Deploy Application'
    dependsOn: Configure_Kubernetes
    jobs:
    - job: Deploy
      steps:
        - task: AzureCLI@2
          displayName: 'Create MySQL secrets'
          inputs:
            azureSubscription: $(azureSubscription)
            scriptType: 'bash'
            scriptLocation: 'inlineScript'
            inlineScript: |
              # Get credentials again to ensure fresh connection
              az aks get-credentials \
                --resource-group $(resourceGroup) \
                --name $(aksCluster) \
                --admin \
                --file /tmp/kubeconfig
              
              export KUBECONFIG=/tmp/kubeconfig
              
              # Create secret
              kubectl create secret generic mysql-secrets \
                --namespace $(namespace) \
                --from-literal=root-password=$(SQLPASS) \
                --from-literal=username=root \
                --from-literal=password=$(SQLPASS) \
                --dry-run=client -o yaml | kubectl apply -f -
              
              # Verify
              kubectl get secret mysql-secrets -n $(namespace)
          env:
            SQLPASS: $(sqlPassword)


        - task: KubernetesManifest@1
          displayName: 'Deploy MySQL'
          inputs:
            kubernetesServiceEndpoint: $(kubernetesServiceConnection)
            action: 'deploy'
            namespace: $(namespace)
            manifests: |
              $(System.DefaultWorkingDirectory)/manifests/mysql-deployment.yaml
              $(System.DefaultWorkingDirectory)/manifests/mysql-service.yaml

        - script: |
            export KUBECONFIG=$(Pipeline.Workspace)/kubeconfig/config
            kubectl wait --namespace $(namespace) --for=condition=ready pod -l app=mysql --timeout=300s
          displayName: 'Wait for MySQL'

        - task: KubernetesManifest@1
          displayName: 'Deploy Backend'
          inputs:
            kubernetesServiceConnection: $(kubernetesServiceConnection)
            action: 'deploy'
            namespace: $(namespace)
            manifests: |
              $(System.DefaultWorkingDirectory)/manifests/backend-deployment.yaml
              $(System.DefaultWorkingDirectory)/manifests/backend-service.yaml

        - task: KubernetesManifest@1
          displayName: 'Deploy Frontend'
          inputs:
            kubernetesServiceConnection: $(kubernetesServiceConnection)
            action: 'deploy'
            namespace: $(namespace)
            manifests: |
              $(System.DefaultWorkingDirectory)/manifests/frontend-deployment.yaml
              $(System.DefaultWorkingDirectory)/manifests/frontend-service.yaml

        - script: |
            export KUBECONFIG=$(Pipeline.Workspace)/kubeconfig/config
            echo "##vso[task.setvariable variable=frontendUrl]http://$(kubectl get svc frontend -n $(namespace) -o jsonpath='{.status.loadBalancer.ingress[0].ip}')"
            echo "Access your application at: http://$(kubectl get svc frontend -n $(namespace) -o jsonpath='{.status.loadBalancer.ingress[0].ip}')"
          displayName: 'Get Frontend URL'
