name: CI/CD Pipeline

on:
  push:
    branches:
      - dummy
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # # BACKEND: Build and Push Docker Image
      # - name: Set up JDK 21
      #   uses: actions/setup-java@v3
      #   with:
      #     distribution: 'temurin'
      #     java-version: '21'

      # - name: Build Spring Boot JAR
      #   run: |
      #     cd billingsystem
      #     mvn clean package -DskipTests

      # - name: Build Backend Docker Image
      #   run: |
      #     cd billingsystem
      #     docker build -t jyothika2832/billing-backend:latest -f ../Dockerfile.backend .

      # # FRONTEND: Build Angular & Push Docker Image
      # - name: Install Node.js
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: '18'

      # - name: Install Angular Dependencies & Build
      #   run: |
      #     cd billingfront
      #     npm install
      #     npm run build --prod

      # - name: Build Frontend Docker Image
      #   run: |
      #     cd billingfront
      #     docker build -t jyothika2832/billing-frontend:latest -f ../Dockerfile.frontend ..

      # # Push Docker Images to Docker Hub
      # - name: Login to Docker Hub
      #   run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # - name: Push Backend Image
      #   run: docker push jyothika2832/billing-backend:latest

      # - name: Push Frontend Image
      #   run: docker push jyothika2832/billing-frontend:latest
       # ---- uncomment for build---
      
      
        # - name: Start SSH agent and Add key
        # run: |


      - name: Set up SSH key
        
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          eval "$(ssh-agent -s)" # Start SSH agent
          echo "${{ secrets.SSH_PASSPHRASE }}" | ssh-add ~/.ssh/id_rsa # Add key with passphrase
          ssh-add -l # Debug List loaded keys

      - name: Add Server SSH Key to known_hosts
        run: |
          
          ssh-keyscan -H localhost >> ~/.ssh/known_hosts
          
          chmod 644 ~/.ssh/known_hosts  

      # - name: Install SSH key
      #   uses: shimataro/ssh-key-action@v2
      #   with:
      #     key: ${{ secrets.SSH_PRIVATE_KEY }}
      #     known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
      
      # Deploy the containers
      - name: Deploy to Server
        run: |

          ssh -vvv jimmy@localhost "echo 'SSH works!'" <<EOF
            docker pull jyothika2832/billing-backend:latest
            docker pull jyothika2832/billing-frontend:latest
            cd ..
            docker-compose down
            docker-compose up -d --force-recreate
          EOF
